# has to be next to .git folder
sudo: required
services:
  - docker

before_script:
  - cd flow

before_install:
  - docker build -t adam/docker -f Dockerfile.dev .

# do not prompt for user input after end of tests
script:
  - docker run adam/docker npm test -- --coverage