version: "3"

services: 
  ngnix:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - "3050:80" #nginx routing to client or api
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server # context specifies workdir
    volumes: 
      - /home/node_modules
      - ./server:/home # apply local changes to container
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /home/node_modules
      - ./client:/home
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /home/node_modules
      - ./worker:/home